server:
  port: 8081

spring:
  rabbitmq:
    template:
      receive-timeout: 30000

---
spring:
  profiles: jms-template, jms-listener
# The values given here are actually the default values. But they are explicitly
# set here as an example of setting the Artemis properties.
  jms:
    template:
      receive-timeout: 2
  artemis:
    host: localhost
    port: 61616
    user: webuser
    password: 1Lik3Pi774
    embedded:
      enabled: false
    
---
spring:
  profiles: kafka-listener
    
  kafka:
    bootstrap-servers:
    - localhost:9092
    template:
      default-topic: pizzacloud.orders.topic
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: pizzacloud_kitchen
      properties:
        spring.json.trusted.packages: pizza
      
      
      
      
      