spring:
  rabbitmq:
    template:
      exchange: pizacloud.orders
      routing-key: kitchens.central

---
spring:
  profiles: prod

  rabbitmq:
    host: rabbit.pizzacloud.com
    port: 5673
    username: webuser
    password: 1lik3Pi774