# Amongst different properties, this one also sets the credentials for the application that will be interacting with
# the broker (The credentials are optional).
spring:
  jms:
    template:
      default-destination: pizzacloud.outgoing.order.queue
  artemis:
    host: localhost
    port: 61616
    user: webuser
    password: letm31n
    embedded:
      enabled: false
    
---
# None of these properties will actually work as configured for this profile. This is just an example.
spring:
  profiles: production
    
  artemis:
    host: artemis.pizzacloud.com
    port: 61617
    user: tacoweb
    password: l3tm31n