security:
  user:
    name: buzz
    password: infinity

pizza:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10
      
#logging:
#  level:
#    org.springframework.data.rest: debug

spring:
  data:
    rest:
      base-path: /api

---
spring:
  profiles: prod
  
  datasource:
    url: jdbc:mysql://localhost/pizzacloud
    username: pizzauser
    password: pizzapassword
    
logging:
  level:
    pizzas: WARN
    
