CREATE TABLE country (
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);

/*CREATE TABLE SPITTER (
    ID INTEGER NOT NULL PRIMARY KEY,
    USERNAME VARCHAR2(255) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL,
    FIRSTNAME VARCHAR2(255) NOT NULL,
    LASTNAME VARCHAR2(255) NOT NULL,
    IMAGE_BASE64 VARCHAR2(255) NOT NULL
);

CREATE TABLE SPITTLE (
    ID INTEGER NOT NULL PRIMARY KEY,
    MESSAGE VARCHAR2(255) NOT NULL,
    TIME TIMESTAMP NOT NULL,
    LATITUTE DOUBLE NOT NULL,
    LONGITUDE DOUBLE NOT NULL
);*/


